let t=localStorage.getItem("aarogyam_superadmin_token")||"",root=document.getElementById("sa");
const esc=x=>String(x??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
async function api(u,o={}){o.headers={...(o.headers||{}),...(t?{Authorization:"Bearer "+t}:{})};const r=await fetch(u,o),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||"Request failed");return j}
function login(){root.innerHTML='<div class="login"><div class="login-card"><div class="brand">✚ Aarogyam</div><div class="eyebrow">Private control panel</div><h2>Super Admin</h2><p class="muted">Owner-only system management.</p><label>EMAIL</label><input id="e" autocomplete="username"><label>PASSWORD</label><input id="p" type="password" autocomplete="current-password"><button class="primary" onclick="doLogin()">Enter Super Admin</button></div></div>'}
async function doLogin(){try{const j=await api("/api/superadmin/login",{method:"POST",body:new URLSearchParams({email:document.getElementById("e").value,password:document.getElementById("p").value})});t=j.access_token;localStorage.setItem("aarogyam_superadmin_token",t);boot()}catch(x){alert(x.message)}}
function shell(){root.innerHTML='<div class="shell"><aside class="side"><div class="brand">✚ Aarogyam</div><div class="eyebrow">Super Admin</div><div class="menu"><button onclick="show(\'dashboard\')">Dashboard</button><button onclick="show(\'centres\')">Centres</button><button onclick="show(\'monitoring\')">Monitoring</button><button onclick="show(\'activity\')">Activity</button><button onclick="show(\'settings\')">System Settings</button><button onclick="show(\'security\')">Security</button><button onclick="logout()">Sign out</button></div></aside><div class="main"><header class="top"><b>Private Control Panel</b><span id="who"></span></header><nav class="mobile-nav"><button onclick="show(\'dashboard\')">Dashboard</button><button onclick="show(\'centres\')">Centres</button><button onclick="show(\'monitoring\')">Monitoring</button><button onclick="show(\'settings\')">Settings</button></nav><div class="wrap"><section id="dashboard" class="section active"></section><section id="centres" class="section"></section><section id="monitoring" class="section"></section><section id="activity" class="section"></section><section id="settings" class="section"></section><section id="security" class="section"></section></div></div></div>';loadMe();dashboard()}
async function loadMe(){const j=await api("/api/superadmin/me");document.getElementById("who").textContent=j.email}
function show(id){document.querySelectorAll(".section").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");({dashboard,centres,monitoring,activity,settings,security}[id])()}
async function dashboard(){const d=await api("/api/superadmin/dashboard");document.getElementById("dashboard").innerHTML='<div class="eyebrow">System overview</div><h1>Aarogyam Control Centre</h1><div class="grid">'+card("Total centres",d.centres)+card("Active centres",d.active_centres)+card("Suspended",d.suspended_centres)+card("Reports",d.reports)+card("Pending verification",d.pending_verifications)+card("Payment pending",d.payment_pending)+card("Credits sold",d.credits_sold)+card("WhatsApp failed",d.wa_failed)+'</div><div class="two"><div class="card"><h3>Business</h3><p><b>Revenue:</b> ₹'+Number(d.revenue_inr).toFixed(2)+'</p><p><b>Credit price:</b> ₹'+Number(d.credit_price_inr).toFixed(2)+'</p><p><b>WhatsApp queue:</b> '+d.wa_pending+' pending/processing/retry</p></div><div class="card"><h3>Quick actions</h3><button class="primary" onclick="show(\'centres\')">Manage centres</button> <button onclick="show(\'monitoring\')">Open monitoring</button></div></div>'}
function card(label,n){return '<div class="card"><div class="eyebrow">'+label+'</div><div class="num">'+n+'</div></div>'}
async function centres(){const a=await api("/api/superadmin/centres");document.getElementById("centres").innerHTML='<div class="eyebrow">Tenant management</div><div class="page-head"><div><h1>Diagnostic Centres</h1><p class="muted">Create, inspect, activate, suspend and manage centre credits.</p></div><button class="primary" onclick="createCentre()">+ Add centre</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Centre</th><th>Status</th><th>Credits</th><th>Reports</th><th>WhatsApp</th><th>Template</th><th>Last activity</th><th></th></tr></thead><tbody>'+a.map(c=>'<tr><td>#'+c.id+'</td><td><b>'+esc(c.name)+'</b><br><small>'+esc(c.email)+'</small></td><td><span class="status '+(c.enabled?"ok":"danger-status")+'">'+(c.enabled?"ACTIVE":"SUSPENDED")+'</span></td><td>'+c.credits+'</td><td>'+c.reports+'</td><td><span class="status '+(c.whatsapp_enabled?"ok":"")+'">'+(c.whatsapp_enabled?"ON":"OFF")+'</span></td><td>'+(c.template_configured?"READY":"—")+'</td><td>'+formatDate(c.last_activity)+'</td><td><button onclick="details('+c.id+')">Details</button> <button onclick="adjust('+c.id+','+c.credits+')">Credits</button> <button onclick="toggleCentre('+c.id+','+c.enabled+')">'+(c.enabled?"Suspend":"Activate")+'</button></td></tr>').join("")+'</tbody></table></div></div>'}
function formatDate(x){return x?new Date(x).toLocaleString():"—"}
async function createCentre(){const name=prompt("Centre name:");if(!name)return;const email=prompt("Centre login email:");if(!email)return;const password=prompt("Temporary password (minimum 10 characters):");if(!password)return;const credits=prompt("Starting credits:",10);try{const j=await api("/api/superadmin/centres",{method:"POST",body:new URLSearchParams({name,email,password,credits})});alert("Centre created. ID: #"+j.centre_id);centres()}catch(x){alert(x.message)}}
async function toggleCentre(id,current){if(!confirm((current?"Suspend":"Activate")+" centre #"+id+"?"))return;try{await api("/api/superadmin/centres/"+id+"/status",{method:"PUT",body:new URLSearchParams({enabled:String(!current)})});centres()}catch(x){alert(x.message)}}
async function adjust(id,current){const v=prompt("New credit balance for centre #"+id,current);if(v===null)return;try{await api("/api/superadmin/centres/"+id+"/credits",{method:"PUT",body:new URLSearchParams({credits:v})});centres()}catch(x){alert(x.message)}}
async function details(id){try{const d=await api("/api/superadmin/centres/"+id),c=d.centre;const reports=d.reports.map(r=>"<tr><td>#"+r.id+"</td><td>"+esc(r.patient_name||"—")+"</td><td>"+esc(r.status)+"</td><td>"+esc(r.payment)+"</td><td>"+formatDate(r.created_at)+"</td></tr>").join("");const tx=d.transactions.map(x=>"<tr><td>"+formatDate(x.created_at)+"</td><td>"+esc(x.type)+"</td><td>"+x.credits+"</td><td>₹"+Number(x.amount_inr||0).toFixed(2)+"</td></tr>").join("");document.getElementById("centres").innerHTML='<div class="eyebrow">Centre details</div><button onclick="centres()">← Back to centres</button><h1>'+esc(c.name)+'</h1><div class="grid">'+card("Credits",c.credits)+card("Status",c.enabled?"ACTIVE":"SUSPENDED")+card("WhatsApp",c.whatsapp_enabled?"ON":"OFF")+card("Template",c.template_configured?"READY":"NOT SET")+'</div><div class="card"><p><b>Login:</b> '+esc(c.email)+'</p><p><b>UPI:</b> '+esc(c.upi_id||"Not configured")+'</p><p><b>Created:</b> '+formatDate(c.created_at)+'</p></div><div class="card"><h3>Recent reports</h3><div class="table-wrap"><table class="table"><tr><th>ID</th><th>Patient</th><th>Status</th><th>Payment</th><th>Date</th></tr>'+reports+'</table></div></div><div class="card"><h3>Credit ledger</h3><div class="table-wrap"><table class="table"><tr><th>Date</th><th>Type</th><th>Credits</th><th>Amount</th></tr>'+tx+'</table></div></div>'}catch(x){alert(x.message)}}
async function monitoring(){const d=await api("/api/superadmin/monitoring");document.getElementById("monitoring").innerHTML='<div class="eyebrow">Operations</div><h1>System Monitoring</h1><div class="card"><h3>Reports waiting for technician verification</h3>'+miniTable(["Report","Centre","Patient","Created"],d.ocr_review.map(x=>["#"+x.id,"#"+x.centre_id,esc(x.patient||"—"),formatDate(x.created_at)]))+'</div><div class="card"><h3>Payment pending</h3>'+miniTable(["Report","Centre","Patient","Payment","Created"],d.payment_pending.map(x=>["#"+x.id,"#"+x.centre_id,esc(x.patient||"—"),esc(x.payment),formatDate(x.created_at)]))+'</div><div class="card"><h3>WhatsApp queue / failures</h3>'+miniTable(["Job","Centre","Report","Kind","Status","Attempts","Error"],d.whatsapp.map(x=>["#"+x.id,"#"+x.centre_id,"#"+x.report_id,esc(x.kind),esc(x.status),x.attempts,esc(x.error||"—")]))+'</div>'}
function miniTable(head,rows){return '<div class="table-wrap"><table class="table"><tr>'+head.map(x=>"<th>"+x+"</th>").join("")+"</tr>"+rows.map(r=>"<tr>"+r.map(x=>"<td>"+x+"</td>").join("")+"</tr>").join("")+'</table></div>'}
async function activity(){const a=await api("/api/superadmin/activity");document.getElementById("activity").innerHTML='<div class="eyebrow">System events</div><h1>Activity</h1><div class="card">'+miniTable(["Date","Centre","Report","Event","Message"],a.map(x=>[formatDate(x.created_at),"#"+x.centre_id,(x.report_id?"#"+x.report_id:"—"),esc(x.kind),esc(x.message)]))+'</div>'}
async function settings(){const s=await api("/api/superadmin/settings");document.getElementById("settings").innerHTML='<div class="eyebrow">Integrations & pricing</div><h1>System Settings</h1><div class="card"><h3>Razorpay</h3><div class="row"><div><label>MODE</label><select id="rm"><option>test</option><option>live</option></select></div><div><label>KEY ID</label><input id="rk" value="'+esc(s.razorpay_key_id)+'"></div></div><label>KEY SECRET</label><input id="rs" type="password" placeholder="Leave blank to keep current secret"><label>WEBHOOK SECRET</label><input id="rw" type="password" placeholder="Leave blank to keep current secret"><p>Checkout: <span class="status '+(s.razorpay_configured?"ok":"")+'">'+(s.razorpay_configured?"CONFIGURED":"NOT CONFIGURED")+'</span> &nbsp; Webhook: <span class="status '+(s.razorpay_webhook_configured?"ok":"")+'">'+(s.razorpay_webhook_configured?"CONFIGURED":"NOT CONFIGURED")+'</span></p></div><div class="card"><h3>WhatsApp Cloud API</h3><div class="row"><div><label>PROVIDER</label><select id="wp"><option>mock</option><option>meta</option></select></div><div><label>PHONE NUMBER ID</label><input id="wn" value="'+esc(s.whatsapp_phone_number_id||"")+'"></div></div><label>ACCESS TOKEN</label><input id="wt" type="password" placeholder="Leave blank to keep current token"></div><div class="card"><h3>Credits & pricing</h3><label>PRICE PER CREDIT (INR)</label><input id="cp" type="number" min="0.01" step="0.01" value="'+esc(s.credit_price_inr)+'"><div class="actions"><button class="primary" onclick="saveSettings()">Save system settings</button></div></div>';document.getElementById("rm").value=s.razorpay_mode;document.getElementById("wp").value=s.whatsapp_provider}
async function saveSettings(){try{const body=new URLSearchParams({razorpay_mode:document.getElementById("rm").value,razorpay_key_id:document.getElementById("rk").value,razorpay_key_secret:document.getElementById("rs").value,razorpay_webhook_secret:document.getElementById("rw").value,whatsapp_provider:document.getElementById("wp").value,whatsapp_token:document.getElementById("wt").value,whatsapp_phone_number_id:document.getElementById("wn").value,credit_price_inr:document.getElementById("cp").value});await api("/api/superadmin/settings",{method:"PUT",body});alert("Settings saved");settings()}catch(x){alert(x.message)}}
function security(){document.getElementById("security").innerHTML='<div class="eyebrow">Account protection</div><h1>Security</h1><div class="card"><h3>Change Super Admin password</h3><label>CURRENT PASSWORD</label><input id="oldpw" type="password"><label>NEW PASSWORD</label><input id="newpw" type="password"><p class="muted">Use at least 10 characters.</p><button class="primary" onclick="changePw()">Change password</button></div>'}
async function changePw(){try{await api("/api/superadmin/password",{method:"PUT",body:new URLSearchParams({current_password:document.getElementById("oldpw").value,new_password:document.getElementById("newpw").value})});alert("Password changed")}catch(x){alert(x.message)}}
function logout(){localStorage.removeItem("aarogyam_superadmin_token");t="";login()}
async function boot(){if(!t)return login();try{await api("/api/superadmin/me");shell()}catch(x){localStorage.removeItem("aarogyam_superadmin_token");t="";login()}}boot();