let token=localStorage.getItem("aarogyam_token")||"",me=null;
const app=document.getElementById("app");
const esc=x=>String(x??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
async function api(u,o={}){o.headers={...(o.headers||{}),...(token?{Authorization:"Bearer "+token}:{})};const r=await fetch(u,o);const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||("Request failed ("+r.status+")"));return j}
function showError(e){app.innerHTML='<div class="wrap"><div class="card"><h2>Aarogyam could not load</h2><p>'+esc(e?.message||e)+'</p><button class="primary" onclick="login()">Open Login</button></div></div>'}
async function downloadPDF(id){try{const r=await fetch("/api/reports/"+id+"/download",{headers:{Authorization:"Bearer "+token}});if(!r.ok)throw Error("PDF download failed");const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="Aarogyam_Report_"+id+".pdf";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){alert(e.message)}}
const nav=()=>'<div class="wrap"><div class="nav"><button onclick="dash()">Dashboard</button><button onclick="capture()">New Report</button><button onclick="reports()">Reports</button><button onclick="notes()">Notifications</button><button onclick="settings()">Settings</button><button onclick="logout()">Logout</button></div></div>';
function login(){app.innerHTML='<div class="wrap"><div class="card" style="max-width:430px;margin:12vh auto"><h2>Centre Login</h2><div class="field"><label>Email</label><input id="email"></div><div class="field"><label>Password</label><input id="password" type="password"></div><button class="primary" onclick="doLogin()">Login</button><button onclick="createCentre()">Create centre</button></div></div>'}
async function doLogin(){try{const j=await api("/api/login",{method:"POST",body:new URLSearchParams({email:document.getElementById("email").value,password:document.getElementById("password").value})});token=j.access_token;localStorage.setItem("aarogyam_token",token);await boot()}catch(e){alert(e.message)}}
async function createCentre(){const name=prompt("Centre name"),email=prompt("Email"),password=prompt("Password");if(!name||!email||!password)return;try{const j=await api("/api/bootstrap",{method:"POST",body:new URLSearchParams({name,email,password})});token=j.access_token;localStorage.setItem("aarogyam_token",token);await boot()}catch(e){alert(e.message)}}
function logout(){localStorage.removeItem("aarogyam_token");token="";login()}
async function boot(){if(!token)return login();try{me=await api("/api/me");document.getElementById("user").textContent=me.name||"";await dash()}catch(e){localStorage.removeItem("aarogyam_token");token="";login()}}
async function dash(){const r=await api("/api/reports");app.innerHTML=nav()+'<div class="wrap"><div class="grid"><div class="card"><b>Reports</b><h2>'+r.length+'</h2></div><div class="card"><b>Credits</b><h2>'+me.credits+'</h2></div><div class="card"><b>Core flow</b><p>Image → OCR → Verify → PDF → Payment → WhatsApp</p></div></div><div class="card"><h3>Recent reports</h3>'+rows(r.slice(0,8))+'</div></div>'}
function capture(){app.innerHTML=nav()+'<div class="wrap"><div class="card"><h2>New Report</h2><p class="muted">Capture analyzer/report images. No patient registration required.</p><input id="imgs" type="file" accept="image/*" multiple><br><br><button class="primary" onclick="upload()">OCR & Review</button></div></div>'}
async function upload(){const el=document.getElementById("imgs");if(!el.files.length)return alert("Choose at least one image");const f=new FormData();[...el.files].forEach(x=>f.append("files",x));try{const j=await api("/api/reports/upload",{method:"POST",body:f});verify(j.report.id,j.extracted)}catch(e){alert(e.message)}}
function testRow(t={},i=0){return '<div class="test-card"><div class="test-title"><span>Test result '+(i+1)+'</span><button type="button" class="remove-test" onclick="this.closest(\\'.test-card\\').remove()">Remove</button></div><div class="test-fields"><div class="field"><label>Property / Test</label><input data-k="name" placeholder="OCR-extracted test name" value="'+esc(t.name)+'"></div><div class="field"><label>Result / Value</label><input data-k="value" placeholder="OCR-extracted result" value="'+esc(t.value)+'"></div><div class="field"><label>Unit</label><input data-k="unit" placeholder="Unit (if present)" value="'+esc(t.unit)+'"></div></div></div>'}
function verify(id,d){const p=d.patient||{},tests=d.tests||[];app.innerHTML=nav()+'<div class="wrap"><div class="card verify-card"><h2>Verify Report #'+id+'</h2><p class="muted">Review the information extracted from the uploaded report image. Every detected test is shown separately so the property, result and unit are easy to verify.</p><div class="grid">'+[['name','Patient name'],['age','Age'],['sex','Sex'],['phone','WhatsApp number'],['code','Patient ID']].map(a=>'<div class="field"><label>'+a[1]+'</label><input id="v_'+a[0]+'" value="'+esc(p[a[0]])+'"></div>').join("")+'</div><h3>Extracted test results</h3><p class="muted small-note">The system decides which properties appear here from the OCR result. No specific test type is assumed.</p><div id="tests">'+(tests.length?tests.map((t,i)=>testRow(t,i)).join(""):'<div class="empty-tests">No test results were extracted. Add the result manually below if it is visible on the report.</div>')+'</div><button type="button" onclick="addTest()">+ Add test result</button> <button class="primary" onclick="approve('+id+')">Approve & Generate PDF</button></div></div>'}
function addTest(){const el=document.getElementById("tests");const n=el.querySelectorAll(".test-card").length;const empty=el.querySelector(".empty-tests");if(empty)empty.remove();el.insertAdjacentHTML("beforeend",testRow({},n))}
async function approve(id){const d={patient:{name:document.getElementById("v_name").value,age:document.getElementById("v_age").value,sex:document.getElementById("v_sex").value,phone:document.getElementById("v_phone").value,code:document.getElementById("v_code").value},tests:[...document.querySelectorAll(".test-card")].map(x=>Object.fromEntries([...x.querySelectorAll("[data-k]")].map(i=>[i.dataset.k,i.value])))};const f=new FormData();f.append("data",JSON.stringify(d));try{await api("/api/reports/"+id+"/verify",{method:"POST",body:f});await pay(id)}catch(e){alert(e.message)}}
async function pay(id){const s=await api("/api/settings");app.innerHTML=nav()+'<div class="wrap"><div class="card"><h2>Report #'+id+'</h2><p>The generated PDF is printed onto your uploaded centre template when a template is configured.</p><button class="primary" onclick="downloadPDF('+id+')">Download Generated PDF</button><hr><h3>Payment & WhatsApp</h3>'+(s.whatsapp_enabled?'<div class="field"><label>Patient charge ₹</label><input id="amt" type="number" min="0" step=".01"></div><div class="field"><label>Payment</label><select id="ps"><option value="PAID">Paid</option><option value="DUE">Due / Pending</option></select></div><button class="primary" onclick="savePay('+id+')">Save payment</button>':'<p class="muted">WhatsApp is OFF. No patient message will be sent.</p>')+'</div></div>'}
async function savePay(id){try{await api("/api/payments/"+id,{method:"POST",body:new URLSearchParams({amount:document.getElementById("amt")?.value||0,status:document.getElementById("ps")?.value||"PAID"})});alert("Saved. Automation queued.");await reports()}catch(e){alert(e.message)}}
async function reports(){const r=await api("/api/reports");app.innerHTML=nav()+'<div class="wrap"><div class="card"><h2>Reports</h2><input id="search" placeholder="Search patient, ID or WhatsApp" oninput="filterReports()"><div id="reportlist">'+rows(r)+'</div></div></div>'}
async function filterReports(){const r=await api("/api/reports?search="+encodeURIComponent(document.getElementById("search").value));document.getElementById("reportlist").innerHTML=rows(r)}
function rows(r){return r.length?'<table class="table"><tr><th>#</th><th>Patient</th><th>Status</th><th>Payment</th><th>PDF</th></tr>'+r.map(x=>'<tr><td>'+x.id+'</td><td>'+esc(x.patient_name)+'</td><td><span class="badge">'+x.status+'</span></td><td>'+x.payment+'</td><td>'+(x.pdf_path?'<button onclick="downloadPDF('+x.id+')">Download</button>':'')+'</td></tr>').join("")+'</table>':'<p class="muted">No reports</p>'}
async function notes(){const n=await api("/api/notifications");app.innerHTML=nav()+'<div class="wrap"><div class="card"><h2>Notification Center</h2>'+n.map(x=>'<div class="card"><b>'+esc(x.kind)+'</b><p>'+esc(x.message)+'</p><small>'+x.created_at+'</small></div>').join("")+'</div></div>'}
async function settings(){const s=await api("/api/settings");app.innerHTML=nav()+'<div class="wrap"><div class="card"><h2>Centre Settings</h2><div class="field"><label>Enable WhatsApp</label><select id="wa"><option value="false">OFF</option><option value="true" '+(s.whatsapp_enabled?"selected":"")+' >ON</option></select></div><div class="field"><label>Active UPI</label><input id="upi" value="'+esc(s.upi_id)+'"></div><p>Credits: <b>'+s.credits+'</b> · Credit price: ₹'+s.credit_price_inr+'</p><button class="primary" onclick="saveSettings()">Save</button><h3>Custom PDF template</h3><p class="muted">Upload the centre’s blank PDF template. Generated reports will be overlaid onto this template.</p><input id="tpl" type="file" accept=".pdf"><button onclick="uploadTemplate()">Upload Template</button></div></div>'}
async function saveSettings(){try{await api("/api/settings",{method:"PUT",body:new URLSearchParams({whatsapp_enabled:document.getElementById("wa").value,upi_id:document.getElementById("upi").value})});alert("Saved");await settings()}catch(e){alert(e.message)}}
async function uploadTemplate(){const el=document.getElementById("tpl");if(!el.files[0])return alert("Choose a PDF");const f=new FormData();f.append("file",el.files[0]);try{await api("/api/settings/template",{method:"POST",body:f});alert("Template saved. Future generated reports will use it.")}catch(e){alert(e.message)}}
window.addEventListener("error",e=>{if(app && !app.innerHTML.trim())showError(e.error||e.message)});
window.addEventListener("unhandledrejection",e=>{if(app && !app.innerHTML.trim())showError(e.reason||"Unexpected error")});
boot().catch(showError);